#pragma once

#include "neug/compiler/planner/operator/logical_operator.h"
namespace neug {
namespace planner {
/**
 * Generated by UnionAliasMapOptimizer to guarantee all subqueries have the same
 * output schema.
 */
class LogicalAliasMap : public LogicalOperator {
 public:
  explicit LogicalAliasMap(const binder::expression_vector& srcExprs,
                           const binder::expression_vector& dstExprs,
                           std::shared_ptr<LogicalOperator> child)
      : LogicalOperator{LogicalOperatorType::ALIAS_MAP, std::move(child)},
        srcExprs{srcExprs},
        dstExprs{dstExprs} {}

  void computeFactorizedSchema() override {
    copyChildSchema(0);
    schema->clearExpressionsInScope();
  }

  void computeFlatSchema() override {
    copyChildSchema(0);
    schema->clearExpressionsInScope();
  }

  inline std::string getExpressionsForPrinting() const override {
    return std::string{};
  }

  std::unique_ptr<LogicalOperator> copy() override {
    return make_unique<LogicalAliasMap>(srcExprs, dstExprs,
                                        children[0]->copy());
  }

  binder::expression_vector getSrcExprs() const { return srcExprs; }
  binder::expression_vector getDstExprs() const { return dstExprs; }

 private:
  binder::expression_vector srcExprs;
  binder::expression_vector dstExprs;
};
}  // namespace planner
}  // namespace neug