/**
 * Copyright 2020 Alibaba Group Holding Limited.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file is originally from the Kùzu project
 * (https://github.com/kuzudb/kuzu) Licensed under the MIT License. Modified by
 * Zhou Xiaoli in 2025 to support Neug-specific features.
 */

#pragma once
#include "neug/compiler/binder/bound_statement.h"

namespace neug {
namespace binder {

class BoundImportDatabase final : public BoundStatement {
 public:
  BoundImportDatabase(std::string filePath, std::string query,
                      std::string indexQuery)
      : BoundStatement{common::StatementType::IMPORT_DATABASE,
                       BoundStatementResult::createSingleStringColumnResult()},
        filePath{std::move(filePath)},
        query{std::move(query)},
        indexQuery{std::move(indexQuery)} {}

  std::string getFilePath() const { return filePath; }
  std::string getQuery() const { return query; }
  std::string getIndexQuery() const { return indexQuery; }

 private:
  std::string filePath;
  // We concatenate queries based on the schema.cypher, copy.cypher, and
  // macro.cypher files generated by exporting the database, resulting in
  // queries such as "create node table xxx; create rel table xxx; copy from
  // xxxx;".
  std::string query;
  std::string indexQuery;
};

}  // namespace binder
}  // namespace neug
